apiVersion: v1
kind: Namespace
metadata:
  name: in-cluster-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: in-cluster-sa
  namespace: in-cluster-ns
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: in-cluster-sa
  name: in-cluster-secret
  namespace: in-cluster-ns
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: in-cluster-role
  namespace: in-cluster-ns
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - '*'
  - nonResourceURLs:
      - /
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: in-cluster-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: in-cluster-role
subjects:
  - kind: ServiceAccount
    name: in-cluster-sa
    namespace: in-cluster-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: in-cluster-systemdiscovery-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:discovery
subjects:
  - kind: ServiceAccount
    name: in-cluster-sa
    namespace: in-cluster-ns